In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import scipy.stats
import pylab
import datetime
from time import time
import seaborn as sns
sns.set()

#time series Libraries
import statsmodels.graphics.tsaplots as sgt 
from statsmodels.tsa.arima.model import ARIMA
from scipy.stats.distributions import chi2
import statsmodels.tsa.stattools as sts
from statsmodels.tsa.stattools import adfuller

In [2]:
raw_csv_data = pd.read_csv("Complete_Sentech_Tower_Data.csv")

In [3]:
sentech_data= raw_csv_data.copy()

,Date,Air_temp,RH,DewPoint,Rain,Pressure,Efield,Lightning_Warnings,Reset_secs,_Normalized_Efield,_Normalized_Warnings
0,2021-11-01 00:00:00,18.83013,44.34569,6.449132,0.0,823.9045,-31.68846,0.0,0.0,-0.001249,0.0
1,2021-11-01 00:15:00,15.88538,60.16803,8.188042,0.0,824.1832,-23.84491,0.0,0.0,-0.000939,0.0
2,2021-11-01 00:30:00,15.17229,67.91439,9.302760,0.0,824.1583,-23.84614,0.0,0.0,-0.000940,0.0
3,2021-11-01 00:45:00,14.64727,71.04126,9.468879,0.0,824.1239,-23.22135,0.0,0.0,-0.000915,0.0
4,2021-11-01 01:00:00,14.49834,72.94492,9.719332,0.0,823.9849,-23.84927,0.0,0.0,-0.000940,0.0
...,...,...,...,...,...,...,...,...,...,...,...
11419,2022-02-27 22:45:00,16.28638,76.22140,12.107980,0.0,827.9321,-14.43517,0.0,0.0,-0.000569,0.0
11420,2022-02-27 23:00:00,15.94644,79.59342,12.436280,0.0,827.6857,-15.37659,0.0,0.0,-0.000606,0.0
11421,2022-02-27 23:15:00,15.81320,81.01760,12.576650,0.0,827.6407,-17.25920,0.0,0.0,-0.000680,0.0
11422,2022-02-27 23:30:00,15.98598,82.16581,12.960260,0.0,827.4928,-17.88704,0.0,0.0,-0.000705,0.0
11423,2022-02-27 23:45:00,15.31052,85.83740,12.966850,0.0,827.4857,-16.63182,0.0,0.0,-0.000655,0.0